services:
  backend:
    image: chsubinn/cineai-be
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:1521/cineAI
      SPRING_DATASOURCE_USERNAME: sa
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_GRANT_TYPE: ${KAKAO_CLIENT_GRANT_TYPE}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}
      GROQ_API_KEY: ${GROQ_API_KEY}
    networks:
      - network
    depends_on:
      - db
      

  frontend:
    image: chsubinn/cineai-fe
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - network
  
  db:
    container_name: h2
    image: oscarfonts/h2:latest
    ports:
      - 1521:1521
      - 8081:81
    environment:
      H2_OPTIONS: -ifNotExists
    # volumes:
    #   - ./h2/:/opt/h2-data
    restart: always
    networks:
      - network

networks:
  network:
    driver: bridge
